name: Test PAT Secret

on:
  workflow_dispatch:   # bisa dijalankan manual dari tab Actions

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Cek apakah PAT ada
        run: |
          if [ -z "${{ secrets.PAT }}" ]; then
            echo "❌ PAT Secret TIDAK ADA"
            exit 1
          else
            echo "✅ PAT Secret berhasil dibaca"
          fi

      - name: Print sebagian token (masked)
        run: |
          TOKEN="${{ secrets.PAT }}"
          PREFIX=$(echo $TOKEN | cut -c1-4)
          SUFFIX=$(echo $TOKEN | rev | cut -c1-4 | rev)
          echo "🔑 PAT Secret = ${PREFIX}****${SUFFIX}"
