name: Project Board Automation

on:
  issues:
    types: [opened]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/achaendus12-spec/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
